### ISSUE TITLE
I18n

### ISSUE THREAD

**Issue by noisegratte** [braincrafted/bootstrap-bundle#122]
Hi,

Could you add translation feature to your bundle's templates. Example, in menu.html.twig in order to translate inputs' labels and in flash.html.twig to translate messages ?

Thx

**Comment by paul-mesnilgrente** [comment]
I think that
>the full flexibility of translation libraries

 would be to have just to add ``->setExtra('translation_domain', 'AppBundle')`` at the end of the ``addChild`` is much simpler than pass the translator to the service and add a lot lines code the template or overwrite only to add a ``|trans``
