### ISSUE TITLE
Radio & Checkbox Inline Style ?

### ISSUE THREAD

**Issue by khyor** [braincrafted/bootstrap-bundle#174]
Hi,

how to set the class '.radio-inline' to items radio or checkbox for a ChoiceType ?

the class exist in bootstrap.css but i don't see in braincrafted how to setting up from the FormType of my Form ?

**Comment by florianeckerstorfer** [comment]
I am now closing some old issues, please reopen if still relevant.

**Comment by truckee** [comment]
Thanks for adding this capability.  For some reason, adding this to a field definition causes the field's label not to appear.  With the following in builder

```
->add('reasons', EntityType::class, array(
    'class' => 'ManaClientBundle:Reason',
    'choice_label' => 'reason',
    'label' => 'Insufficient food: ',
    'expanded' => true,
    'multiple' => true,
    'attr' => [
        'style' => 'inline',
    ],
    'query_builder' => function(EntityRepository $er) {
        return $er->createQueryBuilder('r')
                ->orderBy('r.reason', 'ASC')
                ->where("r.enabled=1");
    },
))
```

and 

```
        <div class="col-md-8">
            {{ form_row(form.reasons) }}
        </div>
```

the display is:

![reasons](https://cloud.githubusercontent.com/assets/2782760/15522414/086437a4-21c7-11e6-9481-add09f972856.png)

If I try adding `{{ form_label(form.reasons) }}` I get nothing.  The label needs to be added manually.

**Comment by truckee** [comment]
I discovered that changing to `'class' => 'form-inline'` allowed the label to appear when using `{{ form_row(form.reason) }}`, and that this effect did not require the `dev-develop` branch. So I withdraw my above issue.
