### ISSUE TITLE
Generate list-group navigation

### ISSUE THREAD

**Issue by tiagobrito** [braincrafted/bootstrap-bundle#180]
Like we do to generate stacked-pills: `{{ knp_menu_render(menu, { 'style': 'stacked-pills' }) }}`, we should be able to create 'list-group': `{{ knp_menu_render(menu, { 'style': 'list-group' }) }}` as described here: http://getbootstrap.com/components/#list-group

**Comment by florianeckerstorfer** [comment]
I am now closing some old issues, please reopen if still relevant.
