### ISSUE TITLE
design where form row uses form_input_group is flawed

### ISSUE THREAD

**Issue by mvrhov** [braincrafted/bootstrap-bundle#183]
I've just found out that due to twig's shortcomings and the way form theme is written it's impossible to use theme inheritance and style any widget differently.

e.g If we take and date widget for an example.
The date widget is configured as a `single_text` and sf form component will thus convert the input type to the `date` type. However if we want to use a custom date picker everywhere, the input type should really be of type `text` and then some other attribute should be set. We would also like to prepend/append an icon to the specific field and do that inside a form template instead of in each form or when calling `form_row`.

The problem is that you can't really do that, the `form_input_group` is rendered from the `form_row` and then the `form_input_group` renders the actual `form_widget`.

No one could try

```jinja
{% block date_widget %}
{% spaceless %}
    {% if widget == 'single_text' %}
        {# next 3 lines mv#}
        {% set type = 'text' %}
        {% set attr = attr|merge({'data-type': 'date'}) %}
        {% set input_group = {'prepend': '.icon-calendar'|parse_icons} %}

        {{ block('form_input_group') }}
    {% else %}
        {% set attr = attr|merge({ 'class': 'bootstrap-date' }) %}
        <div {{ block('widget_container_attributes') }}>
            {{ date_pattern|replace({
                '{{ year }}':  form_widget(form.year),
                '{{ month }}': form_widget(form.month),
                '{{ day }}':   form_widget(form.day),
            })|raw }}
        </div>
    {% endif %}
{% endspaceless %}
{% endblock date_widget %}
```

..but this won't work as expected. One could get input group inside input group if some particular date widgets should use the size. The other thing is that the first 2 set's won't have any effect as their values won't be passed into the final widget because `form_widget(form)` inside `form_input_group` will be called by default parameters (different context),
This means that there is no way in simply adding an icon to the `form_type` via theme inheritance.

**Comment by florianeckerstorfer** [comment]
I am now closing some old issues, please reopen if still relevant.
