### ISSUE TITLE
Pimple / Silex Version

### ISSUE THREAD

**Issue by dominikzogg** [braincrafted/bootstrap-bundle#236]
Hello @florianeckerstorfer 

I am working on a copy of your bundle v 2.0, to get a version for pimple / silex https://github.com/saxulum/saxulum-bootstrap-provider. Would prefere, if you could extract some parts (most as it seems) as a library (would help) and extend it with the bundle.

Regards @dominikzogg

**Comment by florianeckerstorfer** [comment]
I am now closing some old issues, please reopen if still relevant.

**Comment by dominikzogg** [comment]
@florianeckerstorfer i am still interessted to spilt up the code in integration (bundle) code and libary code (which also contains templates)
