### ISSUE TITLE
cant dump assets because the config hardlinks to vendor/jquery/jquery

### ISSUE THREAD

**Issue by ghost** [braincrafted/bootstrap-bundle#262]
The jquery/jquery vendor is not a existing vendor/package in packagist.. 

This breaks dumping assets? "The source file "vendor/jquery/jquery/jquery-1.10.2.js" does not exist."

The only reference to this file i can find resides in this bundle, in the DI configuration.

**Comment by Sydney-o9** [comment]
The problem is in your config file:

````
braincrafted_bootstrap:
    jquery_path: %kernel.root_dir%/../vendor/jquery/jquery/jquery-1.10.2.js
````
to whatever version is the current one:
````
braincrafted_bootstrap:
    jquery_path: %kernel.root_dir%/../vendor/jquery/jquery/jquery-1.11.1.js
````
