### ISSUE TITLE
Single checkbox misaligned in horizontal form

### ISSUE THREAD

**Issue by bostaf** [braincrafted/bootstrap-bundle#273]
Hello,
First of all thanks for the great bundle!

I have an issue with generating checkbox in horizontal form. Here's an excerpt from the official bundle doc (http://bootstrap.braincrafted.com/components.html#forms):

![Excerpt from doc](https://cloud.githubusercontent.com/assets/4865922/3596897/9ae7c716-0ccb-11e4-93aa-269c4e128102.png)

There are two kind of checkboxes at the bottom of the form: multi ("Gender") and single ("Accept terms").

My question is: **is it desired that the single checkbox is misaligned (pulled to the leftmost)?** 

Here's my example, where "Active" is a boolean property of the entity:

![Excerpt from my](https://cloud.githubusercontent.com/assets/4865922/3597120/f2f52d8e-0ccd-11e4-8410-2d36fa9a9214.png)

There's an example of how that single checkbox should get rendered in Twitter Bootstrap doc (http://getbootstrap.com/css/#forms-horizontal):

![Excerpt from TB](https://cloud.githubusercontent.com/assets/4865922/3597203/af70be38-0cce-11e4-96b2-c97264e71668.png)

...which is achieved by adding offset to "make up" for missing label in front of the checkbox:

    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <div class="checkbox">
                <label>
                    <input type="checkbox"> Remember me
                </label>
            </div>
        </div>
    </div>

BootstrapBundle renders the boolean property this way:

    <div class="form-group">
        <div class="checkbox">
            <label for="my_xbundle_m_active" class="required">
                <input id="my_xbundle_m_active" name="my_xbundle_m[active]" required="required" value="1" type="checkbox"> Active
            </label>
        </div>
    </div>

...like missing the parent div (the one with offset) for the checkbox div.

Is it a bug or a feature? :)
Thanks!

**Comment by chasen** [comment]
I would also like to see this be the default, and have to pass false to align_with_widget to have it be the other way

**Comment by florianeckerstorfer** [comment]
I am now closing some old issues, please reopen if still relevant.
