### ISSUE TITLE
Form error class when twig "form.vars.valid" is true

### ISSUE THREAD

**Issue by malberts** [braincrafted/bootstrap-bundle#310]
There is a problem relating to how `form.vars.valid` can be true while at the same time having errors linked to the form item (`form.vars.errors`). There is an upstream Symfony issue related to this (https://github.com/symfony/symfony/issues/7737).

In my case I was testing a form with the following setup:
 - file upload
 - checkbox (unmapped, with a `True()` constraint)

I wanted to break the form intentionally to test the form error when having file(s) uploaded that are larger than the PHP `post_max_size` value. The following happens:
 - I get the global error message for the post size violation
 - The checkbox gets the error message but not the `has-error` class

The second point happens here because `form.vars.valid` is true becase as per the referenced issue, the form is not seen as submitted. However, the validation is still triggered and the checkbox has an error.

Since that issue is not resolved, I want to discuss here what the suggested method for the theme would be.

I changed the form twig file by replacing `{% if not form.vars.valid %}` with `{% if (not form.vars.valid or form.vars.errors|length) %}`. This might be overkill and testing for errors might be enough, but I think there could be cases where the element is invalid but the errors aren't linked to it directly (for example if the errors are bubbled to the form root).

I am using version 2.1.

**Comment by florianeckerstorfer** [comment]
I am now closing some old issues, please reopen if still relevant.
