### ISSUE TITLE
[JS] Trigger event on Add and Remove from collection (sugestion)

### ISSUE THREAD

**Issue by tlfbrito** [braincrafted/bootstrap-bundle#311]
This there a way to catch add/remove events from bc-bootstrap-collection ? If not, shouldn't we fire event to allow people subscribe them?

Thanks for this bundle and your work.

**Comment by raoulclais** [comment]
Is it possible to fire an event right after the collection has been updated ?

Something like this ?
```
$this.trigger('bc-collection-field-before-remove');
var listElement = $this.closest('li').remove();
$this.trigger('bc-collection-field-after-remove');
```
