### ISSUE TITLE
FilterException while loading less filter

### ISSUE THREAD

**Issue by mkoziorowski** [braincrafted/bootstrap-bundle#321]
Hi

I have some issue with FilterException inside the assetic LessFilter.php while loading the filter. There is a script that's going to be executed in a separate process, one of lines in the script looks like this:

<pre><code>
new(less.Parser)(%s).parse(%s, function(e, tree) {
</code></pre>

It looks like the author wants to create a new instance of less.Parser class and then execute a 'parse' method on it. The problem is when i open parser.js file from less module files I see that Parser class has a constructor with 3 arguments but the script is passing only the first argument.
That's my issue but I really don't know what to do with this.

If this is only some versioning mismatch, I have the latest versions of Assetic and Less, so does anybody have idea how to solve this issue?

Thanks

**Comment by sandello-alkr** [comment]
I have solved the same issue @bOnepain had.
For me downgrading less worked:
<code>sudo npm install less@1.7.5 -g</code>
