### ISSUE TITLE
Runtime Exception vendor/jquery/jquery/jquery-1.11.1.js" does not exist.

### ISSUE THREAD

**Issue by ghost** [braincrafted/bootstrap-bundle#338]
```
 "require": {
    "php": ">=5.3.3",
    "symfony/symfony": "2.6.1",
    "doctrine/orm": "~2.2,>=2.2.3",
    "doctrine/doctrine-bundle": "~1.2",
    "twig/extensions": "~1.0",
    "symfony/assetic-bundle": "~2.3",
    "symfony/swiftmailer-bundle": "~2.3",
    "symfony/monolog-bundle": "~2.4",
    "sensio/distribution-bundle": "~3.0",
    "sensio/framework-extra-bundle": "~3.0",
    "incenteev/composer-parameter-handler": "~2.0",

    "leaseweb/doctrine-pdo-dblib": "1.0.2",
    "knplabs/knp-menu": "~2.0",
    "knplabs/knp-menu-bundle": "~2.0",
    "braincrafted/bootstrap-bundle": "dev-develop",
    "twbs/bootstrap": "3.0.*",
    "twbs/bootstrap-sass": "3.3.*",
    "jquery/jquery":  "1.10.*"

},
```

I have the above requirements in my composer.json file but when i run php app/console assetic:dump
I get this error.

[RuntimeException]  
  The source file "/Users/steve_dev/Sites/work/imsl_bio/app/../vendor/jquery/jquery/jquery-1.11.1.js" does not exist.

**Comment by metamaker** [comment]
Can I somehow specify other version of jQuery (not 1.11.1) which I want used?

**Comment by florianeckerstorfer** [comment]
Yes. You can disable the automatic Assetic configuration and define it yourself. Then you can use whatever version of jQuery (as long as its compatible with Bootstrap). See more information in the [docs](http://bootstrap.braincrafted.com/getting-started.html#configuration).

**Comment by metamaker** [comment]
Cool, it works fine! Thank you! :)
