### ISSUE TITLE
Can not find namespaces

### ISSUE THREAD

**Issue by jnnkm** [braincrafted/bootstrap-bundle#348]
Hey, 
i'm having troubles with the namespaces ,i tried several version numbers, (1.4, 2.0, dev-master,  dev-develop). I tried all of those versions with both namespaces for the Bundle whether:

 new Braincrafted\Bundle\BootstrapBundle\BraincraftedBootstrapBundle(), 
 or
new Bc\Bundle\BootstrapBundle\BcBootstrapBundle(),

oddly enough this code used to work in exact this way until it was pushed and pulled into a git repo.
When running:
php app/console server:run
it returns this error:
Class 'Braincrafted\Bundle\BootstrapBundle\BraincraftedBootstrapBundle' not found in /path/to/repo/app/AppKernel.php on line 19

this is the structure of the project
![bildschirmfoto 2015-01-17 um 22 21 07](https://cloud.githubusercontent.com/assets/6465434/5790418/71f51e54-9e97-11e4-86ef-8b16434a1535.png)

appkernel.php
![bildschirmfoto 2015-01-17 um 22 24 10](https://cloud.githubusercontent.com/assets/6465434/5790423/a8d16a90-9e97-11e4-8a71-4e1f100da354.png)

composer.json
![bildschirmfoto 2015-01-17 um 22 24 27](https://cloud.githubusercontent.com/assets/6465434/5790426/b0520400-9e97-11e4-9e0b-50ad9a76b998.png)

Any Ideas how to fix the namespace to find the bundle in the appkernel ? 
Thanks.

**Comment by florianeckerstorfer** [comment]
The namespace in `1.4.x` and `1.5.x` was `Bc\Bundle\BootstrapBundle\BcBootstrapBundle` and was changed to `Braincrafted\Bundle\BootstrapBundle\BraincraftedBootstrapBundle` in >=2.0
