### ISSUE TITLE
horizontal style doesn't work with repeated

### ISSUE THREAD

**Issue by Alumbrados** [braincrafted/bootstrap-bundle#349]
```php
$builder->add('password', 'repeated', array(
    'type' => 'password'
));
```
in combination with

```twig
{{ form_row(form.password, {'style': 'horizontal'}) }}
```

Results in default rendering. Adding attributes for label_col, widget_col and col_size doesn't get added to the output.

**Comment by florianeckerstorfer** [comment]
This should work. Does the Bootstrap styling works for you with the `form` or `form_widget` tag?

**Comment by Alumbrados** [comment]
Nope, i can force it with {{ bootstrap_set_style('horizontal') }} tho

**Comment by florianeckerstorfer** [comment]
That is weird. Do you have configured the bundle correctly? Set up Twig (or auto configure?)

**Comment by florianeckerstorfer** [comment]
I am now closing some old issues, please reopen if still relevant.
