### ISSUE TITLE
No commands in braincrafted:bootstrap

### ISSUE THREAD

**Issue by niqt** [braincrafted/bootstrap-bundle#357]
Symfony 2.3.25 (php 5.5.9), ubuntu server, with less, after running php app/console braincrafted:bootstrap:install i have:
[InvalidArgumentException]                                                
  There are no commands defined in the "braincrafted:bootstrap" namespace.

**Comment by sandello-alkr** [comment]
Check if you've enabled the bundle in AppKernel

**Comment by niqt** [comment]
yes, you have right!  I wrote in the old AppKernel. Sorry
