### ISSUE TITLE
Array to string conversion

### ISSUE THREAD

**Issue by bogdaniel** [braincrafted/bootstrap-bundle#369]
public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('email', 'email', array(
            'label' => false,
            'attr' => array(
                'placeholder' => 'E-Mail',
                'input_group' => array('prepend' => '@')
            ),
            'constraints' => array(
                new NotBlank(array('message' => 'Email-ul nu ar trebui sa fie gol')),
                new Email(array('message' => 'Adresa e-mail invalida'))
            ),
        ))
            ->add('Trimite', 'submit', array('attr' => array('class' => 'save btn btn-primary')));
    }

An exception has been thrown during the rendering of a template ("Notice: Array to string conversion") in form_div_layout.html.twig at line 326

Any ideas guys ?

**Comment by nifr** [comment]
Your error looks similar to #115 - what version of the bundle are you using?

**Comment by bogdaniel** [comment]
i think i installed 2.1.* i solved this problem then encountered another error and so on and finally in reset to an earlier commit and gonna do it my way :-D altho  using this bundle .. would help alot :)

**Comment by stefita** [comment]
Placeholder should be outside the `attr` array, not sure if the same goes for input_group, but the error could be caused by that.
