### ISSUE TITLE
mixing with symfony bootstrap_3_layout.html.twig ??

### ISSUE THREAD

**Issue by craigh** [braincrafted/bootstrap-bundle#371]
Sorry to ask a support-style question here. I'm just wondering if there is any conflict with symfony's new bootstrap form theme (`bootstrap_3_layout.html.twig` or `bootstrap_3_horizontal_layout.html.twig`) and this bundle.

My current (somewhat temporary) solution is a customized version of symfony's theme, but was curious about using this bundle instead. Have you found any issues?

**Comment by JohnieWalker** [comment]
Don't use symfony bootstrap theme if using Braincrafted. I had symfony bootstrap theme enabled and had some issues (don't remember exactly)

**Comment by florianeckerstorfer** [comment]
@JohnieWalker is right. BootstrapBundle comes with it's one theme. Some of the features of BootstrapBundle will not work with the theme bundled with Symfony.
