### ISSUE TITLE
knp_menu_base.html.twig does not exists

### ISSUE THREAD

**Issue by bigfoot90** [braincrafted/bootstrap-bundle#387]
The file ```knp_menu_base.html.twig``` does not exists in ```@BraincraftedBootstrap/Menu/bootstrap.html.twig```
```
  - braincrafted/bootstrap-bundle (v2.1.2)
  - knplabs/knp-menu-bundle (v1.1.2)
```

**Comment by florianeckerstorfer** [comment]
Sorry that I didn't respond earlier, but the template is part of KnpMenu, not KnpMenuBundle.

https://github.com/KnpLabs/KnpMenu/tree/master/src/Knp/Menu/Resources/views
