### ISSUE TITLE
sameas deprecated

### ISSUE THREAD

**Issue by dkisselev** [braincrafted/bootstrap-bundle#398]
Just noticed the SF profiler complaining about this one, sameas has been deprecated in favor of 'same as'

http://twig.sensiolabs.org/doc/deprecated.html#tests

https://github.com/braincrafted/bootstrap-bundle/blob/develop/Resources/views/Form/bootstrap.html.twig#L39 (and many other places)

I might go through and make the changes myself but just leaving this here in case someone else is already working on things and can toss up a PR to make the changes before I get to it.

**Comment by benr77** [comment]
Just submitted a PR #399

**Comment by dkisselev** [comment]
#399 and a few other related commits were merged to I'm assuming all the instances have now been patched up.
