### ISSUE TITLE
Error rendering form

### ISSUE THREAD

**Issue by bnd170** [braincrafted/bootstrap-bundle#411]
Hi, i get this error when render a form in template:

> An exception has been thrown during the rendering of a template ("Catchable Fatal Error: Argument 1 passed to Symfony\Component\Translation\Loader\ArrayLoader::flatten() must be of the type array, integer given, called in /vendor/symfony/symfony/src/Symfony/Component/Translation/Loader/ArrayLoader.php on line 28 and defined") in BraincraftedBootstrapBundle:Form:bootstrap.html.twig at line 586

It worked until yesterday

**Comment by florianeckerstorfer** [comment]
This looks like a problem with you translations. Did you change anything with them in the last day?

**Comment by bnd170** [comment]
Nope, my app doesnt translatable atm

2015-12-16 14:34 GMT+01:00 Florian Eckerstorfer <notifications@github.com>:

**Comment by florianeckerstorfer** [comment]
Did you disable translation completely? BootstrapBundle uses the translation keys in it's template and you have to have translation enabled.

**Comment by bnd170** [comment]
Fixed, a problem with git and cache was the error. :) Not an issue from Braincrafted. Sorry for open that.

**Comment by florianeckerstorfer** [comment]
No problem
