### ISSUE TITLE
Collection form

### ISSUE THREAD

**Issue by fcpauldiaz** [braincrafted/bootstrap-bundle#415]
I'm trying to use the collection type with this bundle like this

```php
  ->add('arrayDiagnosticos', 'bootstrap_collection', [
                    'type' => 'entity',
                    'allow_add' => true,
                    'allow_delete' => true,
                     'add_button_text'    => 'Add Select',
                    'delete_button_text' => 'Delete Select',
                    'sub_widget_col'     => 9,
                    'button_col'         => 3,
                    'options'=>[
                       'empty_value' => 'Seleccionar Diagnóstico',
                        'class' => 'AppBundle:Diagnostico',
                        'required' => true,
                        'label' => 'Buscador de Diagnósticos',
                        'attr' => [
                            'class' => 'select2',
                        ],

                    ]
                ])
```
Twig
```Twig
{{form.arrayDiagnosticos}}
```
But only the add button is rendered and when I click it, it does nothing. I thought this bundle included the javascript out of the box. I think that the javascript is the issue.

**Comment by dkisselev** [comment]
It does/should handle that for you by default.

Make sure that assetic is properly configured and that you've included the 'Basic Template' from the [Getting Started](http://bootstrap.braincrafted.com/getting-started.html) docs in your layout (the braincrafted collection JS is compiled into the boostrap.js asset)

The javascript might also be a little finicky about form names, although I don't think it should make a difference, try rendering out the form all at once (with {{ form(form) }} to see if that helps.

**Comment by fcpauldiaz** [comment]
I manually copied the [collection.js](https://github.com/braincrafted/bootstrap-bundle/blob/develop/Resources/js/bc-bootstrap-collection.js) and it worked.
