### ISSUE TITLE
Flash messages via javascript

### ISSUE THREAD

**Issue by fcpauldiaz** [braincrafted/bootstrap-bundle#416]
Does this bundle support flash messages via javascript?

something like this?
```javascript
<script language="javascript">
    $(function () {
        $.flash({ type: "success", message: "You are a success!" });  
    });
 </script>
```

**Comment by dkisselev** [comment]
As far as I know, bootstrap doesn't support the type of alerts you're suggesting, so I don't think it would really be in the scope of this bundle, that sounds like a potential jquery plugin that you would just use on its own.

**Comment by fcpauldiaz** [comment]
Thanks for the info @dkisselev
