### ISSUE TITLE
Removed less filter

### ISSUE THREAD

**Issue by fcpauldiaz** [braincrafted/bootstrap-bundle#421]
I just updated to the 2.2.0 version and had this error.

```
[Symfony\Component\Config\Definition\Exception\InvalidConfigurationException]  
  Unrecognized option "less_filter" under "braincrafted_bootstrap"  
```

Was this filter removed or it is a bug? I tried to remove it from the config but then it triggers an Assetic exception.

**Comment by florianeckerstorfer** [comment]
The option has been renamed to `css_preprocessor` (but the documentation is out of date #423)

**Comment by fcpauldiaz** [comment]
Thanks!

**Comment by lisabeyy** [comment]
Thanks a lot !

**Comment by jmeyo** [comment]
can you make documentation version dependent ? that would save some time.

**Comment by melroy89** [comment]
Nobody updates the documentation??

**Comment by cAstraea** [comment]
so how to fix this ? getting this error running composer update on a sandbox project someone else made. 

nvm found it it's the setup in config.yml under braincrafted_bootstrap
