### ISSUE TITLE
documentation out of date

### ISSUE THREAD

**Issue by cam-spacebar** [braincrafted/bootstrap-bundle#423]
BCBS docs for 2.\* here:
http://bootstrap1.braincrafted.com/getting-started

refer to app/config/config.yml option :
less_filter

when  it should be :
css_preprocessor

(caused me a few headaches - first time user)

**Comment by DemonTPx** [comment]
Yep, same problem here... This seems to me like a small BC break. It should accept `less_filter` as an alias of `css_preprocessor` and notify a deprecation warning or something...

**Comment by florianeckerstorfer** [comment]
Documentation has been updated

**Comment by decima** [comment]
http://semver.org/ 
please follow Semantic versioning like symfony and others (minor version should not crash backyard compatibility).
👎
