### ISSUE TITLE
Change button size in bootstrap collection

### ISSUE THREAD

**Issue by fcpauldiaz** [braincrafted/bootstrap-bundle#426]
I need to change the button size in the [bootstrap collection](http://bootstrap.braincrafted.com/playground/forms.html)

Is there a way to add something like:

``` php
 'button_class' => 'btn btn-lg'
```

**Comment by dkisselev** [comment]
We got around this with `'button_class' => 'warning btn-sm',`

It's not perfect but works in the mean time, the button_class field is just appended to the classes as a string concatenated with btn-

**Comment by fcpauldiaz** [comment]
Where do you add the "button_class? When I use the the option "button_class" I get an error. I'm using the 2.2v @dkisselev

**Comment by florianeckerstorfer** [comment]
@fcpauldiaz What error do you get?

**Comment by fcpauldiaz** [comment]
That the button class option doesn't exist. If I add it in the attr it won't throw an error but it doesn't work.
@florianeckerstorfer 

![captura de pantalla 2016-03-18 08 41 44](https://cloud.githubusercontent.com/assets/4523284/13881168/64512a16-ece5-11e5-9cf6-39f0f544dc63.png)

**Comment by florianeckerstorfer** [comment]
I just looked it up and there is currently no way to change the class of the button in collection widget. [see](https://github.com/braincrafted/bootstrap-bundle/blob/develop/Resources/views/Form/bootstrap.html.twig#L108)

You need to overwrite the widget

**Comment by fcpauldiaz** [comment]
Ok, maybe this issue can be marked as a feature.

**Comment by nifr** [comment]
So an implementation of `add_button_attr` and `delete_button_attr` options +  changes to the default widget would be needed? 

Would it be better to add `add_button_options` and `remove_button_options` maybe even?

**Comment by fcpauldiaz** [comment]
I think that is better `add_button_attr`and `delete_button_attr` @nifr

**Comment by salemgolemugoo** [comment]
#450 look please

**Comment by florianeckerstorfer** [comment]
Closed by #450
