### ISSUE TITLE
Configuration doesn't allow HTTP downloads

### ISSUE THREAD

**Issue by melroy89** [braincrafted/bootstrap-bundle#432]
Hi,

By default Composer doesn't allow HTTP downloads (like the jQuery requirement). 

> [Composer\Downloader\TransportException]  
>   Your configuration does not allow connections to http://code.jquery.com/jquery-1.11.1.js. See https://getcomposer.org/doc/06-  
>   config.md#secure-http for details.  

So, please change the code.jQuery.com URL on the following page:
http://bootstrap.braincrafted.com/getting-started.html#installation

From:
http://code.jquery.com/jquery-1.11.1.js
To:
http**s**://code.jquery.com/jquery-1.11.1.js

Thanks!

Kind regards,
Melroy van den berg

**Comment by florianeckerstorfer** [comment]
Fixed in develop
