### ISSUE TITLE
Console is moved

### ISSUE THREAD

**Issue by melroy89** [braincrafted/bootstrap-bundle#433]
Hi,

The console component is moved, from app/ to bin/ folder. Yet again, please update the installer guide:
http://bootstrap.braincrafted.com/getting-started.html#installation

From:
php app/console assetic:dump

To:
php **bin/console** assetic:dump

> Do this for all the app/console lines within the documentation!

Although you also doesn't explain how to install the assetic-bundle component (which is by default NOT installed).

Thanks.

Kind regards,
Melroy van den Berg

**Comment by florianeckerstorfer** [comment]
Fixed in develop
