### ISSUE TITLE
Composer Deprecation Notice

### ISSUE THREAD

**Issue by abastien** [braincrafted/bootstrap-bundle#449]
Followed the installation tutorial and inserted the glyphicons with the scripthandler like explained at http://bootstrap.braincrafted.com/getting-started.html#installation

`{
    ...
    "scripts": {
        "post-install-cmd": [
            ...
            "Braincrafted\\Bundle\\BootstrapBundle\\Composer\\ScriptHandler::install"
        ],
        "post-update-cmd": [
            ...
            "Braincrafted\\Bundle\\BootstrapBundle\\Composer\\ScriptHandler::install"
        ]
    }
    ...
}`

Composer throw me an error message when I run composer update : 
However the fonts are copied but the warning message is annoying.

> > Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::installRequirementsFile
> > Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::prepareDeploymentTarget
> > Deprecation Notice: The callback Braincrafted\Bundle\BootstrapBundle\Composer\ScriptHandler::install declared at /home/www/vendor/braincrafted/bootstrap-bundle/Braincrafted/Bundle/BootstrapBundle/Composer/ScriptHandler.php accepts a Composer\Script\CommandEvent but post-update-cmd events use a Composer\Script\Event instance. Please adjust your type hint accordingly, see https://getcomposer.org/doc/articles/scripts.md#event-classes in phar:///usr/local/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php:289
> > Braincrafted\Bundle\BootstrapBundle\Composer\ScriptHandler::install
> > Copied icon fonts to /home/www/app/../web/fonts.

**Comment by fogs** [comment]
Same here..

**Comment by alex-barylski** [comment]
Can this issue not be closed?

https://github.com/braincrafted/bootstrap-bundle/pull/442

**Comment by abastien** [comment]
@alex-barylski : Yes you're right mate ;) I close it.
