### ISSUE TITLE
Custom assetic config does not overwrite default config

### ISSUE THREAD

**Issue by ChristianVermeulen** [braincrafted/bootstrap-bundle#94]
Hi, I get error message that responsive.less can not be found. Which is correct because there is no responsive.css in bootstrap 3.0.0.

So in app/config.yml I added:

``` yml
    assets:
            bootstrap_css:
                inputs:
                    - %kernel.root_dir%/../vendor/twbs/bootstrap/less/bootstrap.less.test
                filters:
                    - less
                    - cssrewrite
                output: css/bootstrap.css
```

As you can see I added `.test` at the end, because this will show in assetic dump that first the default conf is loaded, and afterwards my custom config.

Here is the output for `assetic:dump -v`

```
Dumping all dev assets.
Debug mode is on.

19:36:21 [file+] /Users/seer/Sites/mcbrommer.com/app/../web/css/bootstrap.css
        /Users/seer/Sites/mcbrommer.com/app/../vendor/twbs/bootstrap/less/bootstrap.less
        /Users/seer/Sites/mcbrommer.com/app/../vendor/twbs/bootstrap/less/responsive.less
        /Users/seer/Sites/mcbrommer.com/app/../vendor/twbs/bootstrap/less/bootstrap.less.test



  [RuntimeException]
  The source file "/Users/seer/Sites/mcbrommer.com/app/../vendor/twbs/bootstrap/less/responsive.less" does not exist.
```

As you can see it first tries to load bootstrap.less and responsive.less before looking at my config. If I put only bootstrap.less, it recognizes the double but still tries to include responsive.less.

How can I stop assetic from including responsive.less??

I am using BS V3.0.0 though

**Comment by TheDagger** [comment]
I'm having this same issue right now
